title: Binah Arhirinmu Utuedor
logo: head.png
description: I am results-driven Data Analyst with more than five years of practical experience working with tools such as Advanced Excel for data modelling and automation, Power BI for interactive dashboards and business intelligence reporting, SQL for efficient data extraction and manipulation, and Python for advanced analytics, automation, and data visualization, to transform complex data into actionable insights and support strategic decision-making. I am adept at working with cross-cultural and cross-functional teams to drive performance improvements. 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
