title: Binah Arhirinmu Utuedor
logo: head.png
description: I am a results-driven Data Analyst with more than five years of hands-on experience working with Advanced Excel for data modelling and automation, Power BI for interactive dashboards and business intelligence reporting, and SQL for efficient data extraction and manipulation. 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
